/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_logorrr_OsxBridge */

#ifndef _Included_app_logorrr_OsxBridge
#define _Included_app_logorrr_OsxBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_logorrr_OsxBridge
 * Method:    registerPath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_app_logorrr_OsxBridge_registerPath
  (JNIEnv *, jclass, jstring);

/*
 * Class:     app_logorrr_OsxBridge
 * Method:    releasePath
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_app_logorrr_OsxBridge_releasePath
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
